#BalhauAPI application configuration file
---
configs:
  webserver:
    binding_host: 0.0.0.0
    port: 5000
    log: false
    env: prod
  database:
    hostname: 192.168.1.14
    schema: postgres
    port: 5432
    user: postgres
    pass: postgres
  folders:
    mediafolder: /tmp/lolada