---
configs:
  remotes:
      - name: The Remote Name
        host: <hostname> //--> 192.168.1.169:122
        user: <ssh_user>
        pass: <ssh_password>
  webserver:
    binding_host: 0.0.0.0
    port: 5000
    log: false
    env: prod
  database:
    hostname: 192.168.1.14
    schema: postgres
    port: 5432
    user: <posgres_user>
    pass: <posgres_password>
  folders:
    mediafolder: /tmp/whynot