---
configs:
  remotes:
      - name: The Remote Name
        host: 192.168.1.169:122
        user: balhau
        pass: gamma-007
  webserver:
    binding_host: 0.0.0.0
    port: 5000
    log: false
    env: prod
  database:
    hostname: 192.168.1.11
    schema: postgres
    port: 32470
    user: postgres
    pass: postgres
  folders:
    mediafolder: /tmp/whynot