[package]
name = "coinscrapper"
version = "0.1.0"
authors = ["balhau <balhau@balhau.net>"]

[dependencies]
#html5ever = "*"
reqwest="0.8.2"
scraper = "0.4.0"
kafka = "0.7"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
